import { MultilingualSummary, StatutoryFlag, ClauseResult, DocType, InvoiceData } from "../types";

export interface RegionalSummaryParams {
  docType: DocType;
  fileName: string;
  clauses: ClauseResult[];
  statutoryViolations: StatutoryFlag[];
  invoice?: InvoiceData;
  language: string;
}

export interface RegionalLabels {
  panelTitle: string;
  panelSubtitle: string;
  corePurposeHeader: string;
  keyObligationsHeader: string;
  highRiskHeader: string;
  recommendedActionHeader: string;
  printBtn: string;
  docTitle: string;
  subTitleHeader: string;
  sec1Title: string;
  sec2Title: string;
  reportLangLabel: string;
  dateLabel: string;
  statuteLabel: string;
  footerNotice1: string;
  footerNotice2: string;
}

export const REGIONAL_UI_LABELS: Record<string, RegionalLabels> = {
  en: {
    panelTitle: "Executive Multilingual Digest",
    panelSubtitle: "1-Page plain-language legal summary generated in regional Indian languages.",
    corePurposeHeader: "Core Purpose & Summary",
    keyObligationsHeader: "Key MSME Obligations & Rights",
    highRiskHeader: "High Risk Factors & Statutory Violations",
    recommendedActionHeader: "Recommended Action for MSME Owner",
    printBtn: "Print 1-Page Report",
    docTitle: "ClauseIQ Legal Memorandum",
    subTitleHeader: "MSME Statutory Legal Intelligence • 100% Local AI",
    sec1Title: "1. Executive Overview & Scope",
    sec2Title: "2. Recommended MSME Action Plan",
    reportLangLabel: "Report Language",
    dateLabel: "Date",
    statuteLabel: "Statute Compliance: MSMED Act 2006 / ICA 1872",
    footerNotice1: "Generated by ClauseIQ On-Device AI Engine • Private & Confidential",
    footerNotice2: "Compliant with Indian Evidence Act 1872 & MSMED Act 2006",
  },
  hi: {
    panelTitle: "कार्यकारी बहुभाषी कानूनी सारांश",
    panelSubtitle: "क्षेत्रीय भारतीय भाषाओं में तैयार 1-पृष्ठीय सरल कानूनी सारांश।",
    corePurposeHeader: "मुख्य उद्देश्य एवं सारांश",
    keyObligationsHeader: "मुख्य MSME दायित्व एवं अधिकार",
    highRiskHeader: "उच्च जोखिम कारक एवं कानूनी उल्लंघन",
    recommendedActionHeader: "MSME उद्यमी के लिए अनुशंसित कानूनी कार्रवाई",
    printBtn: "1-पेज रिपोर्ट प्रिंट करें",
    docTitle: "ClauseIQ कानूनी ज्ञापन (Legal Memorandum)",
    subTitleHeader: "MSME वैधानिक कानूनी विश्लेषण • 100% स्थानीय AI",
    sec1Title: "1. कार्यकारी अवलोकन एवं दायरा",
    sec2Title: "2. अनुशंसित MSME कार्य योजना",
    reportLangLabel: "रिपोर्ट भाषा",
    dateLabel: "दिनांक",
    statuteLabel: "वैधानिक अनुपालन: MSMED अधिनियम 2006 / ICA 1872",
    footerNotice1: "ClauseIQ ऑन-डिवाइस AI इंजन द्वारा तैयार • पूर्णतः गोपनीय एवं सुरक्षित",
    footerNotice2: "भारतीय साक्ष्य अधिनियम 1872 एवं MSMED अधिनियम 2006 के तहत वैध",
  },
  ta: {
    panelTitle: "நிர்வாக பன்மொழி சட்டச் சுருக்கம்",
    panelSubtitle: "பிராந்திய இந்திய மொழிகளில் உருவாக்கப்பட்ட 1 பக்க சட்ட சுருக்கம்.",
    corePurposeHeader: "முக்கிய நோக்கம் & சுருக்கம்",
    keyObligationsHeader: "முக்கிய MSME கடமைகள் & உரிமைகள்",
    highRiskHeader: "அதிக ஆபத்து காரணிகள் & சட்டமீறல்கள்",
    recommendedActionHeader: "MSME உரிமையாளருக்கான பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    printBtn: "1 பக்க அறிக்கையை அச்சிடுக",
    docTitle: "ClauseIQ சட்ட குறிப்பாணை (Legal Memorandum)",
    subTitleHeader: "MSME சட்ட நுண்ணறிவு • 100% உள்ளூர் AI",
    sec1Title: "1. நிர்வாக மேலோட்டம் & வரம்பு",
    sec2Title: "2. பரிந்துரைக்கப்பட்ட MSME செயல் திட்டம்",
    reportLangLabel: "அறிக்கை மொழி",
    dateLabel: "தேதி",
    statuteLabel: "சட்ட இணக்கம்: MSMED சட்டம் 2006 / ICA 1872",
    footerNotice1: "ClauseIQ உள்ளூர் AI எஞ்சின் மூலம் உருவாக்கப்பட்டது • ரகசியமானது",
    footerNotice2: "இந்திய சாட்சியச் சட்டம் 1872 & MSMED சட்டம் 2006 இணக்கமானது",
  },
  te: {
    panelTitle: "ఎగ్జిక్యూటివ్ బహుభాషా చట్టపరమైన సారాంశం",
    panelSubtitle: "ప్రాంతీయ భారతీయ భాషలలో రూపొందించబడిన 1-పేజీ చట్టపరమైన సారాంశం.",
    corePurposeHeader: "ప్రధాన ఉద్దేశ్యం & సారాంశం",
    keyObligationsHeader: "ప్రధాన MSME బాధ్యతలు & హక్కులు",
    highRiskHeader: "అధిక ప్రమాద కారకాలు & చట్ట ఉల్లంఘనలు",
    recommendedActionHeader: "MSME యజమానికి సిఫార్సు చేయబడిన కార్యాచరణ",
    printBtn: "1-పేజీ నివేదికను ముద్రించండి",
    docTitle: "ClauseIQ చట్టపరమైన మెమోరాండమ్",
    subTitleHeader: "MSME చట్టపరమైన విశ్లేషణ • 100% స్థానిక AI",
    sec1Title: "1. ఎగ్జిక్యూటివ్ అవలోకనం & పరిధి",
    sec2Title: "2. సిఫార్సు చేయబడిన MSME కార్యాచరణ ప్రణాళిక",
    reportLangLabel: "నివేదిక భాష",
    dateLabel: "తేదీ",
    statuteLabel: "చట్టపరమైన సమ్మతి: MSMED చట్టం 2006 / ICA 1872",
    footerNotice1: "ClauseIQ ఆన్-డివైస్ AI ఇంజిన్ ద్వారా రూపొందించబడింది • అత్యంత గోప్యమైనది",
    footerNotice2: "భారతీయ సాక్ష్యాల చట్టం 1872 & MSMED చట్టం 2006 కు అనుగుణంగా ఉంది",
  },
  mr: {
    panelTitle: "कार्यकारी बहुभाषिक कायदेशीर सारांश",
    panelSubtitle: "स्थानिक भारतीय भाषांमध्ये तयार केलेला १-पानी सोपा कायदेशीर सारांश.",
    corePurposeHeader: "मुख्य उद्देश आणि सारांश",
    keyObligationsHeader: "प्रमुख MSME कर्तव्ये आणि हक्क",
    highRiskHeader: "उच्च जोखीम घटक आणि कायदेशीर उल्लंघन",
    recommendedActionHeader: "MSME उद्योजकांसाठी शिफारस केलेली कृती",
    printBtn: "१-पानी अहवाल प्रिंट करा",
    docTitle: "ClauseIQ कायदेशीर ज्ञापन (Legal Memorandum)",
    subTitleHeader: "MSME वैधानिक कायदेशीर विश्लेषण • १००% स्थानिक AI",
    sec1Title: "१. कार्यकारी विहंगावलोकन आणि व्याप्ती",
    sec2Title: "२. शिफारस केलेली MSME कृती योजना",
    reportLangLabel: "अहवाल भाषा",
    dateLabel: "दिनांक",
    statuteLabel: "वैधानिक अनुपालन: MSMED कायदा २००६ / ICA १८७२",
    footerNotice1: "ClauseIQ ऑन-डिव्हाइस AI इंजिनद्वारे तयार केलेले • अत्यंत गोपनीय",
    footerNotice2: "भारतीय पुरावा कायदा १८७२ आणि MSMED कायदा २००६ नुसार वैध",
  },
  bn: {
    panelTitle: "কার্যনির্বাহী বহুভাষিক আইনি সারসংক্ষেপ",
    panelSubtitle: "আঞ্চলিক ভারতীয় ভাষায় তৈরি ১-পৃষ্ঠার সহজ আইনি সারাংশ।",
    corePurposeHeader: "মূল উদ্দেশ্য ও সারসংক্ষেপ",
    keyObligationsHeader: "প্রধান MSME দায়বদ্ধতা ও অধিকার",
    highRiskHeader: "উচ্চ ঝুঁকির কারণ ও আইনি লঙ্ঘন",
    recommendedActionHeader: "MSME মালিকের জন্য প্রস্তাবিত পদক্ষেপ",
    printBtn: "১-পৃষ্ঠার রিপোর্ট প্রিন্ট করুন",
    docTitle: "ClauseIQ আইনি স্মারকলিপি (Legal Memorandum)",
    subTitleHeader: "MSME সংবিধিবদ্ধ আইনি বুদ্ধিমত্তা • ১০০% স্থানীয় AI",
    sec1Title: "১. কার্যনির্বাহী পর্যালোচনা ও পরিধি",
    sec2Title: "২. প্রস্তাবিত MSME কর্মপরিকল্পনা",
    reportLangLabel: "রিপোর্ট ভাষা",
    dateLabel: "তারিখ",
    statuteLabel: "সংবিধিবদ্ধ সম্মতি: MSMED আইন ২০০৬ / ICA ১৮৭২",
    footerNotice1: "ClauseIQ অন-ডিভাইস AI ইঞ্জিন দ্বারা তৈরি • গোপনীয়",
    footerNotice2: "ভারতীয় প্রমাণ আইন ১৮৭২ এবং MSMED আইন ২০০৬ এর সাথে সঙ্গতিপূর্ণ",
  },
};

const VIOLATION_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    MSMED_PAYMENT: "MSMED Act 2006 (§15): Payment term exceeds the mandatory 45-day statutory limit for MSME suppliers.",
    MSMED_INTEREST: "MSMED Act 2006 (§16): Delayed payments statutorily accrue compound interest at 3× RBI bank rate.",
    "MSMED-SEC-15": "MSMED Act 2006 (§15): Invoice due date exceeds the statutory 45-day payment cap.",
    ICA_NONCOMPETE: "Indian Contract Act 1872 (§27): Post-termination non-compete covenants are void and unenforceable (Zaheer Khan precedent).",
    ICA_PENALTY: "Indian Contract Act 1872 (§74): Unreasonable liquidated damages or penalty clauses without actual proof of loss are void.",
    ACA_ARBITRATOR: "Arbitration Act 1996 (§12(5)): Unilateral appointment of a sole arbitrator by one party is legally void (Perkins Eastman precedent).",
    ACA_SEAT: "Arbitration Act 1996: Foreign arbitration seat deprives MSME of statutory MSME Samadhaan dispute resolution.",
    INDEMNITY_ASYM: "One-Sided Indemnity: Disproportionate liability shift onto the MSME supplier with zero buyer accountability.",
  },
  hi: {
    MSMED_PAYMENT: "MSMED अधिनियम 2006 (धारा 15): भुगतान की अवधि 45 दिन की कानूनी सीमा से अधिक है, जो MSME विक्रेता के लिए अवैध है।",
    MSMED_INTEREST: "MSMED अधिनियम 2006 (धारा 16): विलंबित भुगतान पर RBI बैंक दर के 3 गुना चक्रवृद्धि ब्याज का वैधानिक अधिकार है।",
    "MSMED-SEC-15": "MSMED अधिनियम 2006 (धारा 15): इनवॉइस की देय तिथि 45 दिन की कानूनी सीमा से अधिक है।",
    ICA_NONCOMPETE: "भारतीय अनुबंध अधिनियम 1872 (धारा 27): अनुबंध समाप्ति के बाद गैर-प्रतिस्पर्धा (Non-Compete) खंड भारत में पूर्णतः अमान्य है।",
    ICA_PENALTY: "भारतीय अनुबंध अधिनियम 1872 (धारा 74): बिना वास्तविक नुकसान साबित किए मनमाना हर्जाना या ज़ब्ती अवैध है।",
    ACA_ARBITRATOR: "मध्यस्थता अधिनियम 1996 (धारा 12(5)): एकतरफा मध्यस्थ (Arbitrator) की नियुक्ति कानूनन अमान्य है (Perkins Eastman निर्णय)।",
    ACA_SEAT: "मध्यस्थता अधिनियम 1996: विदेशी मध्यस्थता स्थल MSME को 'MSME समाधान' फोरम के वैधानिक संरक्षण से वंचित करता है।",
    INDEMNITY_ASYM: "एकतरफा क्षतिपूर्ति (Indemnity): केवल विक्रेता पर संपूर्ण कानूनी एवं वित्तीय जोखिम डालना अनुचित है।",
  },
  ta: {
    MSMED_PAYMENT: "MSMED சட்டம் 2006 (பிரிவு 15): பணம் செலுத்தும் காலம் கட்டாய 45 நாள் சட்டப்பூர்வ வரம்பை விட அதிகமாக உள்ளது.",
    MSMED_INTEREST: "MSMED சட்டம் 2006 (பிரிவு 16): தாமதமான கட்டணங்களுக்கு RBI வங்கி விகிதத்தில் 3 மடங்கு கூட்டு வட்டி பெற உரிமை உண்டு.",
    "MSMED-SEC-15": "MSMED சட்டம் 2006 (பிரிவு 15): இன்வாய்ஸ் பணம் செலுத்தும் காலம் 45 நாள் உச்சவரம்பை மீறுகிறது.",
    ICA_NONCOMPETE: "இந்திய ஒப்பந்தச் சட்டம் 1872 (பிரிவு 27): பணி முடிவுக்குப் பின் தொழில் செய்ய தடை விதிக்கும் பிரிவுகள் செல்லாது.",
    ICA_PENALTY: "இந்திய ஒப்பந்தச் சட்டம் 1872 (பிரிவு 74): முறையான இழப்பு இல்லாமல் விதிக்கப்படும் அதிக அபராதங்கள் சட்டவிரோதம்.",
    ACA_ARBITRATOR: "மத்தியஸ்த சட்டம் 1996 (பிரிவு 12(5)): ஒரு தரப்பு மட்டுமே தன்னிச்சையாக நடுவரை நியமிப்பது சட்டவிரோதமானது.",
    ACA_SEAT: "மத்தியஸ்த சட்டம் 1996: வெளிநாட்டு மத்தியஸ்த இடம் MSME Samadhaan சட்டப்பூர்வ பாதுகாப்பை பறிக்கிறது.",
    INDEMNITY_ASYM: "ஒருதலைப்பட்ச இழப்பீடு: MSME விற்பனையாளர் மீது மட்டுமே முழுப் பொறுப்பையும் சுமத்துவது அநீதி.",
  },
  te: {
    MSMED_PAYMENT: "MSMED చట్టం 2006 (సెక్షన్ 15): చెల్లింపు గడువు చట్టబద్ధమైన 45 రోజుల పరిమితిని మించిపోయింది.",
    MSMED_INTEREST: "MSMED చట్టం 2006 (సెక్షన్ 16): ఆలస్యమైన చెల్లింపులపై RBI బ్యాంక్ రేటుకు 3 రెట్లు చక్రవడ్డీ పొందే హక్కు ఉంది.",
    "MSMED-SEC-15": "MSMED చట్టం 2006 (సెక్షన్ 15): ఇన్వాయిస్ చెల్లింపు తేదీ గరిష్ట 45 రోజుల పరిమితిని దాటింది.",
    ICA_NONCOMPETE: "భారత కాంట్రాక్ట్ చట్టం 1872 (సెక్షన్ 27): ఒప్పందం ముగిసిన తర్వాత పోటీ నిషేధం విధించే నిబంధనలు చెల్లవు.",
    ICA_PENALTY: "భారత కాంట్రాక్ట్ చట్టం 1872 (సెక్షన్ 74): సరైన నష్టం చూపించకుండా విధించే భారీ జరిమానాలు చట్టవిరుద్ధం.",
    ACA_ARBITRATOR: "ఆర్బిట్రేషన్ చట్టం 1996 (సెక్షన్ 12(5)): ఏకపక్షంగా మధ్యవర్తిని నియమించడం చట్టరీత్యా చెల్లదు.",
    ACA_SEAT: "ఆర్బిట్రేషన్ చట్టం 1996: విదేశీ ఆర్బిట్రేషన్ స్థలం MSME సమాధాన్ హక్కులను దూరం చేస్తుంది.",
    INDEMNITY_ASYM: "ఏకపక్ష నష్టపరిహారం: కేవలం MSME విక్రేతపై మాత్రమే పూర్తి బాధ్యతను మోపడం అనుచితం.",
  },
  mr: {
    MSMED_PAYMENT: "MSMED कायदा २००६ (कलम १५): देयकाची मुदत कायद्याने बंधनकारक असलेल्या ४५ दिवसांच्या मर्यादेपेक्षा जास्त आहे.",
    MSMED_INTEREST: "MSMED कायदा २००६ (कलम १६): उशिरा झालेल्या देयकावर RBI बँक दराच्या ३ पट चक्रवाढ व्याज मिळण्याचा हक्क आहे.",
    "MSMED-SEC-15": "MSMED कायदा २००६ (कलम १५): इनव्हॉइस देय मुदत कमाल ४५ दिवसांच्या मर्यादेबाहेर आहे.",
    ICA_NONCOMPETE: "भारतीय करार कायदा १८७२ (कलम २७): करार संपल्यानंतर व्यवसायावर बंधने घालणाऱ्या अटी पूर्णपणे बेकायदेशीर आहेत.",
    ICA_PENALTY: "भारतीय करार कायदा १८७२ (कलम ७४): प्रत्यक्ष नुकसान सिद्ध केल्याशिवाय आकारलेला दंड न्यायालयात टिकत नाही.",
    ACA_ARBITRATOR: "लवाद कायदा १९९६ (कलम १२(५)): एकाच पक्षाने एकतर्फी लवाद (Arbitrator) नियुक्त करणे कायद्याने अवैध आहे.",
    ACA_SEAT: "लवाद कायदा १९९६: परदेशी लवाद केंद्र MSME ला 'MSME Samadhaan' च्या अधिकारापासून वंचित करते.",
    INDEMNITY_ASYM: "एकतर्फी भरपाई: केवळ MSME पुरवठादारावर सर्व कायदेशीर भार टाकणे असंतुलित व अन्यायकारक आहे.",
  },
  bn: {
    MSMED_PAYMENT: "MSMED আইন ২০০৬ (ধারা ১৫): অর্থপ্রদানের মেয়াদ বাধ্যতামূলক ৪৫ দিনের আইনি সীমা অতিক্রম করেছে।",
    MSMED_INTEREST: "MSMED আইন ২০০৬ (ধারা ১৬): বিলম্বিত অর্থপ্রদানের ক্ষেত্রে RBI ব্যাঙ্ক হারের ৩ গুণ চক্রবৃদ্ধি সুদ প্রাপ্য।",
    "MSMED-SEC-15": "MSMED আইন ২০০৬ (ধারা ১৫): ইনভয়েসের অর্থপ্রদানের সময়সীমা ৪৫ দিনের সীমা লঙ্ঘন করে।",
    ICA_NONCOMPETE: "ভারতীয় চুক্তি আইন ১৮৭২ (ধারা ২৭): চুক্তি সমাপ্তির পর প্রতিযোগিতাহীনতার (Non-Compete) ধারা সম্পূর্ণ অকার্যকর।",
    ICA_PENALTY: "ভারতীয় চুক্তি আইন ১৮৭২ (ধারা ৭৪): প্রকৃত ক্ষতি প্রমাণ ছাড়া অযৌক্তিক জরিমানা বা ক্ষতিপূরণ আইনত বাতিল।",
    ACA_ARBITRATOR: "সালিসি আইন ১৯৯৬ (ধারা ১২(৫)): একতরফাভাবে সালিসকারী (Arbitrator) নিয়োগ আইনত অবৈধ।",
    ACA_SEAT: "সালিসি আইন ১৯৯৬: বিদেশি সালিসির স্থান MSME Samadhaan-এর সংবিধিবদ্ধ সুযোগ থেকে বঞ্চিত করে।",
    INDEMNITY_ASYM: "একতরফা ক্ষতিপূরণ: কেবল MSME সরবরাহকারীর উপর সমস্ত ক্ষতিপূরণের দায় চাপানো অন্যায়।",
  },
};

const REGIONAL_TEMPLATES: Record<string, {
  executiveIntroContract: (count: number, riskCount: number) => string;
  executiveIntroInvoice: (num: string, vendor: string, amt: string) => string;
  obligations: string[];
  risksSafe: string;
  adviceViolation: string;
  adviceSafe: string;
}> = {
  en: {
    executiveIntroContract: (count, riskCount) =>
      `Commercial Agreement containing ${count} analyzed clauses. Identified ${riskCount} statutory risk items under Indian MSMED Act 2006 and Indian Contract Act 1872.`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `Tax Invoice #${num} from ${vendor} amounting to ₹${amt}. Evaluated against statutory MSMED Section 15 payment ceilings.`,
    obligations: [
      "Settle all verified invoices within agreed timeframe.",
      "Comply with statutory written notice periods prior to contract termination.",
      "Maintain strict confidentiality of shared business trade secrets.",
      "Comply with GST tax invoice filing and reconciliation deadlines.",
    ],
    risksSafe: "No critical statutory violations detected. Contract terms conform to baseline Indian statutes.",
    adviceViolation:
      "CRITICAL MSME ACTION: Issue formal counter-notice to amend payment terms to maximum 45 days (MSMED Sec 15) and delete post-termination restrictive covenants (ICA Sec 27).",
    adviceSafe:
      "Standard agreement terms. Ready to proceed with standard operational execution after authorized managerial review.",
  },
  hi: {
    executiveIntroContract: (count, riskCount) =>
      `वाणिज्यिक अनुबंध जिसमें ${count} खंडों का विश्लेषण किया गया है। भारतीय MSMED अधिनियम 2006 एवं भारतीय अनुबंध अधिनियम 1872 के तहत ${riskCount} कानूनी जोखिम पहचाने गए हैं।`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `कर चालान (Tax Invoice) #${num}, विक्रेता ${vendor}, कुल राशि ₹${amt}। MSMED धारा 15 की अधिकतम 45 दिन की कानूनी सीमा के आधार पर जाँचा गया।`,
    obligations: [
      "सत्यापित बिलों का भुगतान तय समय सीमा के भीतर करें।",
      "अनुबंध समाप्त करने से पहले औपचारिक लिखित नोटिस अवधि का पालन करें।",
      "साझा की गई व्यावसायिक जानकारी एवं व्यापार गोपनीयता को सुरक्षित रखें।",
      "GST इनवॉइस फाइलिंग एवं टैक्स मिलान समय पर पूरा करें।",
    ],
    risksSafe: "कोई वैधानिक उल्लंघन नहीं पाया गया। अनुबंध की शर्तें भारतीय कानूनों के अनुरूप हैं।",
    adviceViolation:
      "महत्वपूर्ण MSME सलाह: भुगतान अवधि को घटाकर अधिकतम 45 दिन (MSMED धारा 15) करने और गैर-प्रतिस्पर्धा खंड (अनुबंध अधिनियम धारा 27) को हटाने के लिए औपचारिक जवाबी नोटिस भेजें।",
    adviceSafe:
      "अनुबंध सामान्य और सुरक्षित है। आवश्यक प्रशासनिक स्वीकृति के बाद आगे बढ़ सकते हैं।",
  },
  ta: {
    executiveIntroContract: (count, riskCount) =>
      `வணிக ஒப்பந்தம் ${count} பிரிவுகளுடன் பகுப்பாய்வு செய்யப்பட்டது. இந்திய MSMED சட்டம் 2006 மற்றும் ஒப்பந்தச் சட்டம் 1872 இன் கீழ் ${riskCount} சட்டரீதியான அபாயங்கள் கண்டறியப்பட்டுள்ளன.`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `வரி விலைப்பட்டியல் (Invoice) #${num}, விற்பனையாளர் ${vendor}, மொத்த தொகை ₹${amt}. MSMED பிரிவு 15 கட்டாய 45 நாள் வரம்பின் கீழ் சரிபார்க்கப்பட்டது.`,
    obligations: [
      "ஒப்புக்கொள்ளப்பட்ட காலக்கெடுவுக்குள் சரிபார்க்கப்பட்ட கட்டணங்களை செலுத்துங்கள்.",
      "ஒப்பந்தத்தை ரத்து செய்வதற்கு முன் சட்டப்பூர்வ எழுத்துப்பூர்வ அறிவிப்பை வழங்குங்கள்.",
      "வணிக ரகசியங்கள் மற்றும் பரிமாறப்பட்ட தரவுகளின் பாதுகாப்பை உறுதிசெய்க.",
      "GST மற்றும் வரி ஆவணங்களை சரியான நேரத்தில் தாக்கல் செய்யுங்கள்.",
    ],
    risksSafe: "சட்டமீறல்கள் எதுவும் கண்டறியப்படவில்லை. ஒப்பந்த விதிமுறைகள் இணக்கமாக உள்ளன.",
    adviceViolation:
      "முக்கிய MSME நடவடிக்கை: பணம் செலுத்தும் காலத்தை அதிகபட்சம் 45 நாட்களாக மாற்றவும் (MSMED பிரிவு 15) மற்றும் தடை பிரிவுகளை நீக்கவும் அதிகாரப்பூர்வ அறிவிப்பை அனுப்பவும்.",
    adviceSafe:
      "ஒப்பந்த விதிமுறைகள் பாதுகாப்பானவை. உரிய நிர்வாக ஒப்புதலுக்குப் பிறகு தொடரலாம்.",
  },
  te: {
    executiveIntroContract: (count, riskCount) =>
      `వాణిజ్య ఒప్పందంలో ${count} నిబంధనలు విశ్లేషించబడ్డాయి. భారతీయ MSMED చట్టం 2006 మరియు కాంట్రాక్ట్ చట్టం 1872 ప్రకారం ${riskCount} చట్టపరమైన ప్రమాదాలు గుర్తించబడ్డాయి.`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `పన్ను ఇన్వాయిస్ #${num}, విక్రేత ${vendor}, మొత్తం సొమ్ము ₹${amt}. MSMED సెక్షన్ 15 గరిష్ట 45 రోజుల నిబంధన ప్రకారం సమీక్షించబడింది.`,
    obligations: [
      "అంగీకరించిన గడువులోగా చెల్లింపులను పూర్తి చేయండి.",
      "ఒప్పందం రద్దుకు ముందు నిర్దేశిత లిఖితపూర్వక నోటీసును అందించండి.",
      "వ్యాపార రహస్యాలు మరియు గోప్యతా సమాచారాన్ని భద్రపరచండి.",
      "GST ఇన్వాయిస్ మరియు పన్ను వివరాలను సకాలంలో సమర్పించండి.",
    ],
    risksSafe: "ఎటువంటి చట్టపరమైన ఉల్లంఘనలు లేవు. ఒప్పందం నిబంధనలు సరిగ్గా ఉన్నాయి.",
    adviceViolation:
      "ముఖ్యమైన MSME సలహా: చెల్లింపు వ్యవధిని గరిష్టంగా 45 రోజులకు సవరించడానికి (MSMED సెక్షన్ 15) మరియు పోటీ-నిరోధక నిబంధనలను తొలగించడానికి కౌంటర్ నోటీసు ఇవ్వండి.",
    adviceSafe:
      "ఒప్పంద నిబంధనలు సురక్షితంగా ఉన్నాయి. నిర్వహణ ఆమోదం తర్వాత కొనసాగవచ్చు.",
  },
  mr: {
    executiveIntroContract: (count, riskCount) =>
      `व्यावसायिक करार ज्यामध्ये ${count} कलमांचे विश्लेषण करण्यात आले आहे. MSMED कायदा २००६ आणि भारतीय करार कायदा १८७२ अंतर्गत ${riskCount} वैधानिक जोखीम घटक आढळले आहेत.`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `टॅक्स इनव्हॉइस #${num}, पुरवठादार ${vendor}, एकूण रक्कम ₹${amt}. MSMED कलम १५ अंतर्गत कमाल ४५ दिवसांच्या मर्यादेनुसार तपासले गेले.`,
    obligations: [
      "मंजूर देयके ठरलेल्या मुदतीत अदा करावीत.",
      "करार समाप्त करण्यापूर्वी कायदेशीर लेखी नोटीस कालावधीचे पालन करा.",
      "सामायिक केलेली व्यावसायिक माहिती व गोपनीयतेचे रक्षण करा.",
      "GST इनव्हॉइस आणि कर परतावा वेळेवर दाखल करा.",
    ],
    risksSafe: "कोणतेही वैधानिक उल्लंघन आढळले नाही. कराराच्या अटी कायद्यानुसार योग्य आहेत.",
    adviceViolation:
      "महत्त्वाचा MSME सल्ला: पेमेंट मुदत ४५ दिवसांपर्यंत मर्यादित करण्यासाठी (MSMED कलम १५) आणि स्पर्धा-विरोधी अटी वगळण्यासाठी कायदेशीर काउंटर-नोटीस पाठवा.",
    adviceSafe:
      "करार सुरक्षित आहे. आवश्यक प्रशासकीय मंजुरीनंतर स्वाक्षरी करू शकता.",
  },
  bn: {
    executiveIntroContract: (count, riskCount) =>
      `বাণিজ্যিক চুক্তি যার মধ্যে ${count}টি ধারা বিশ্লেষণ করা হয়েছে। ভারতীয় MSMED আইন ২০০৬ এবং ভারতীয় চুক্তি আইন ১৮৭২-এর অধীনে ${riskCount}টি আইনি ঝুঁকি শনাক্ত হয়েছে।`,
    executiveIntroInvoice: (num, vendor, amt) =>
      `ট্যাক্স ইনভয়েস #${num}, বিক্রেতা ${vendor}, মোট মূল্য ₹${amt}। MSMED ধারা ১৫-এর অধীনে সর্বাধিক ৪৫ দিনের অর্থপ্রদানের শর্ত অনুযায়ী যাচাই করা হয়েছে।`,
    obligations: [
      "সম্মত সময়সীমার মধ্যে সমস্ত যাচাইকৃত বিল পরিশোধ করুন।",
      "চুক্তি বাতিলের আগে বিধিবদ্ধ লিখিত নোটিশের মেয়াদ অনুসরণ করুন।",
      "ব্যবসায়িক গোপনীয়তা এবং শেয়ার করা তথ্যের সুরক্ষা নিশ্চিত করুন।",
      "GST চালান এবং কর সংক্রান্ত কাজ সময়মতো সম্পন্ন করুন।",
    ],
    risksSafe: "কোনো বিধিবদ্ধ আইন লঙ্ঘন পাওয়া যায়নি। চুক্তির শর্তাবলী ভারতীয় আইনের সাথে সামঞ্জস্যপূর্ণ।",
    adviceViolation:
      "জরুরি MSME পরামর্শ: অর্থপ্রদানের মেয়াদ সর্বাধিক ৪৫ দিনে নামিয়ে আনার জন্য (MSMED ধারা ১৫) এবং অ-প্রতিযোগিতামূলক ধারা অপসারণের জন্য আনুষ্ঠানিক নোটিশ পাঠান।",
    adviceSafe:
      "চুক্তির শর্তাবলী স্বাভাবিক ও নিরাপদ। অভ্যন্তরীণ অনুমোদনের পর এগিয়ে যাওয়া যেতে পারে।",
  },
};

export function generateRegionalSummary(params: RegionalSummaryParams): MultilingualSummary {
  const lang = REGIONAL_TEMPLATES[params.language] ? params.language : "en";
  const tpl = REGIONAL_TEMPLATES[lang];
  const dict = VIOLATION_TRANSLATIONS[lang] || VIOLATION_TRANSLATIONS.en;

  let execSummary = "";
  if (params.docType === "invoice") {
    const num = params.invoice?.invoiceNumber || "INV-001";
    const vendor = params.invoice?.vendorName || "Vendor / Supplier";
    const amt = (params.invoice?.totalAmount || 0).toLocaleString("en-IN");
    execSummary = tpl.executiveIntroInvoice(num, vendor, amt);
  } else {
    execSummary = tpl.executiveIntroContract(params.clauses.length, params.statutoryViolations.length);
  }

  // Deduplicate violations by ruleId
  const seenRuleIds = new Set<string>();
  const criticalRisks: string[] = [];

  for (const v of params.statutoryViolations) {
    const ruleKey = v.ruleId || v.section || v.citation;
    if (seenRuleIds.has(ruleKey)) continue;
    seenRuleIds.add(ruleKey);

    if (dict[v.ruleId]) {
      criticalRisks.push(dict[v.ruleId]);
    } else if (v.reasoning && v.reasoning.length > 10) {
      const prefix = v.section ? `${v.section}: ` : "";
      criticalRisks.push(`${prefix}${v.reasoning}`);
    } else if (v.citation) {
      const prefix = v.section ? `${v.section}: ` : "";
      criticalRisks.push(`${prefix}${v.citation}`);
    }
  }

  if (criticalRisks.length === 0) {
    criticalRisks.push(tpl.risksSafe);
  }

  const actionableAdvice =
    params.statutoryViolations.length > 0 ? tpl.adviceViolation : tpl.adviceSafe;

  return {
    language: lang,
    executiveSummary: execSummary,
    keyObligations: tpl.obligations,
    criticalRisks,
    actionableAdvice,
  };
}
